dataset:
    jump_rate: 0.3    
    means: [5.0, 10.0]
    stds: [1.0, 1.0]
    num_states: 2
    num_sequences: 4
    sequence_length: 128

training:
    device: "native"
    batch_size: 256
    num_layers: 1
    learning_rate: 5.0e-2
    num_epochs: 100
    init_jump_rate : 0.1