dataset:
    num_states: 2
    jump_rate: 0.3

    emission_type: "normal"
    
    gaussian_means: [5.0, 10.0]
    gaussian_stds: [1.0, 1.0]

    nb_eff_coverages: [10.0, 20.0]
    nb_sampling: [0.1, 0.25]

    bb_alphas: [10., 20.]
    bb_betas: [15., 25.]
    
    num_sequences: 4
    sequence_length: 64

training:
    device: "native"
    compile: 0
    num_workers: 1
    num_layers: 1    
    batch_size: 256
    learning_rate: 5.0e-2
    gradient_threshold: 5.0
    num_epochs: 50
    init_jump_rate : 0.1
    init_means: [3.0, 8.0]
    init_stds: [1.1, 1.1]
    init_alphas: [1.0, 1.0]
    init_betas: [1.0, 1.0]
    init_nb_logits: [1.0, 1.0]
    init_nb_coverage: [1.0, 1.0]